[build]
  command = "npm run build"
  publish = ".next"

# Netlify secrets scanning flags public client keys in the bundle.
# Supabase anon key and URL are safe to expose (RLS enforced) and must be in the client bundle.
# Instruct the scanner to ignore these specific public keys while keeping scanning enabled for others.
[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_SUPABASE_ANON_KEY,NEXT_PUBLIC_SUPABASE_URL"

# Netlify CDN caching for all SSR pages (24h cache, 7-day stale-while-revalidate)
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    Netlify-CDN-Cache-Control = "public, s-maxage=86400, stale-while-revalidate=604800"
    Netlify-Vary = "query"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
